etl:
  raw_data_file: "data/winequality.csv"
  processed_path: "data"
  test_size: 0.2
  random_state: 42

train:
  processed_train: "data/train.csv" 
  ensemble_model: "RandomForestClassifier"
  model_config: {n_estimators: 100, random_state: 42}
  model_path: "model/model.pkl"

# train:
#   processed_train: "data/train.csv" 
#   ensemble_model: "GradientBoostingClassifier"
#   model_config: {n_estimators: 100, random_state: 42}
#   model_path: "model/another_model.pkl"

predict:
  model_path: "model/model.pkl"
  processed_test: "data/test.csv"
  predicted_file: "data/predict.csv"
  export_result: True
